### ISSUE TITLE
wrong deep dependency v0.2.3 by read-pkg-up

### ISSUE THREAD

**Issue by biancode** [node-red/node-red-node-test-helper#36]
TypeError: pathType.dirSync is not a function

      at Function.Object.<anonymous>.module.exports.sync (node_modules/read-pkg/index.js:38:16)
      at Function.Object.<anonymous>.module.exports.sync.opts [as sync] (node_modules/read-pkg-up/index.js:23:16)
      at findRuntimePath (node_modules/node-red-node-test-helper/index.js:37:29)
      at NodeTestHelper.init (node_modules/node-red-node-test-helper/index.js:132:38)
      at new NodeTestHelper (node_modules/node-red-node-test-helper/index.js:78:14)
      at Object.<anonymous> (node_modules/node-red-node-test-helper/index.js:325:18)

fixed by setting     "path-type": "^3.0.0" in my package.json

**Comment by knolleary** [comment]
I've just published 0.2.4 of this module that updates to the latest version of `read-pkg-up` which no longer appears to have a dependency on `path-type`.
