### ISSUE TITLE
Tutorial on unit tests doesn't work

### ISSUE THREAD

**Issue by maxlein** [node-red/node-red-node-test-helper#72]
I am trying to run unit tests like you describe in your example, but it seems to me that the helper is not correctly initialized.

So if I try to load my node, I get an undefined logger:

```
    load(testNode, testFlow, testCredentials, cb) {
        const log = this._log;
        console.log("logger: " + log);  // -> undefined
```

```
logger: undefined

TypeError: Cannot read properties of undefined (reading 'log')
    at Function.spy (node_modules/sinon/lib/sinon/spy.js:156:61)
    at Sandbox.spy (node_modules/sinon/lib/sinon/sandbox.js:328:35)
    at NodeTestHelper.load (node_modules/node-red-node-test-helper/index.js:179:53)
    at Context.<anonymous> (test/lower-case_spec.js:14:16)
    at process.processImmediate (node:internal/timers:476:21)
```

package versions:

```
  "node-red" : {
    "version": ">=2.0.0",
    "nodes": {
      "lower-case": "lower-case.js"
    }
  },
  "dependencies": {
  },
  "devDependencies": {
    "mocha": "^10.2.0",
    "node-red-node-test-helper": "^0.3.2"
  }
```

**Comment by maxlein** [comment]
Ok, the documentation page is outdated...
It's missing `helper.init(require.resolve('node-red'));`
